<<<<<<< Updated upstream
# Generated by Django 3.2.9 on 2021-11-28 15:10
=======
# Generated by Django 2.2 on 2020-11-05 16:53
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
<<<<<<< Updated upstream
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_eng', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
>>>>>>> Stashed changes
                ('price', models.IntegerField()),
                ('img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
<<<<<<< Updated upstream


=======
>>>>>>> Stashed changes
